#pragma checksum "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\DriverMailer\_Layout.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "4E58888D2CA3298175E0F758687A99B332EF3605"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    
    
    public class _Page_Views_DriverMailer__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_DriverMailer__Layout_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/DriverMailer/_Layout.cshtml", 0, 22, true);

WriteLiteral("<!DOCTYPE html>\r\n<html");

EndContext("~/Views/DriverMailer/_Layout.cshtml", 0, 22, true);

BeginContext("~/Views/DriverMailer/_Layout.cshtml", 22, 10, true);

WriteLiteral(" lang=\"en\"");

EndContext("~/Views/DriverMailer/_Layout.cshtml", 22, 10, true);

BeginContext("~/Views/DriverMailer/_Layout.cshtml", 32, 547, true);

WriteLiteral(@">
<head>
    <title>Driver MSM Alert</title>
    <style>
        .main-content {
            margin-left: 60px;
            margin-right: 0;
            margin-top: 0;
            min-height: 100%;
            padding: 0;
        }

        body {
            padding-bottom: 0;
            background-color: #e4e6e9;
            min-height: 100%;
            font-family: 'Open Sans';
            font-size: 13px;
            color: #393939;
            line-height: 1.5;
        }

    </style>

</head>
<body>
    <div");

EndContext("~/Views/DriverMailer/_Layout.cshtml", 32, 547, true);

BeginContext("~/Views/DriverMailer/_Layout.cshtml", 579, 21, true);

WriteLiteral(" class=\"main-content\"");

EndContext("~/Views/DriverMailer/_Layout.cshtml", 579, 21, true);

BeginContext("~/Views/DriverMailer/_Layout.cshtml", 600, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/DriverMailer/_Layout.cshtml", 600, 3, true);

BeginContext("~/Views/DriverMailer/_Layout.cshtml", 603, 8, true);

WriteLiteral("        ");

EndContext("~/Views/DriverMailer/_Layout.cshtml", 603, 8, true);

BeginContext("~/Views/DriverMailer/_Layout.cshtml", 612, 12, false);

            
            #line 29 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\DriverMailer\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
EndContext("~/Views/DriverMailer/_Layout.cshtml", 612, 12, false);

BeginContext("~/Views/DriverMailer/_Layout.cshtml", 624, 94, true);

WriteLiteral("\r\n\r\n        Thank you<br />\r\n        QCT Materials Team!\r\n    </div>\r\n\r\n\r\n\r\n</bod" +
"y>\r\n</html>\r\n");

EndContext("~/Views/DriverMailer/_Layout.cshtml", 624, 94, true);

        }
    }
}
