#pragma checksum "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\IdfOnlyList.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "645EA6B9D25D72AD6F41705A0DD23B31F13FDCC8"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    
    
    public class _Page_Views_IDF_IdfOnlyList_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<MvcChipRequest.ViewModels.AllChipRequestsViewModel>> {
        
#line hidden
        
        public _Page_Views_IDF_IdfOnlyList_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\IdfOnlyList.cshtml"
  
    ViewBag.Title = "IdfOnlyList";

            
            #line default
            #line hidden
BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 115, 33, true);

WriteLiteral("\r\n\r\n<h2>IdfOnlyList</h2>\r\n\r\n<p>\r\n");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 115, 33, true);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 148, 4, true);

WriteLiteral("    ");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 148, 4, true);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 153, 39, false);

            
            #line 10 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\IdfOnlyList.cshtml"
Write(Html.ActionLink("Create New", "Create"));

            
            #line default
            #line hidden
EndContext("~/Views/IDF/IdfOnlyList.cshtml", 153, 39, false);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 192, 41, true);

WriteLiteral("\r\n</p>\r\n<table>\r\n    <tr>\r\n        <th>\r\n");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 192, 41, true);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 233, 12, true);

WriteLiteral("            ");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 233, 12, true);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 246, 46, false);

            
            #line 15 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\IdfOnlyList.cshtml"
       Write(Html.DisplayNameFor(model => model.IsNotFound));

            
            #line default
            #line hidden
EndContext("~/Views/IDF/IdfOnlyList.cshtml", 246, 46, false);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 292, 31, true);

WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 292, 31, true);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 323, 12, true);

WriteLiteral("            ");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 323, 12, true);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 336, 52, false);

            
            #line 18 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\IdfOnlyList.cshtml"
       Write(Html.DisplayNameFor(model => model.ExceptionOccured));

            
            #line default
            #line hidden
EndContext("~/Views/IDF/IdfOnlyList.cshtml", 336, 52, false);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 388, 31, true);

WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 388, 31, true);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 419, 12, true);

WriteLiteral("            ");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 419, 12, true);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 432, 52, false);

            
            #line 21 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\IdfOnlyList.cshtml"
       Write(Html.DisplayNameFor(model => model.ExceptionMessage));

            
            #line default
            #line hidden
EndContext("~/Views/IDF/IdfOnlyList.cshtml", 432, 52, false);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 484, 49, true);

WriteLiteral("\r\n        </th>\r\n        <th></th>\r\n    </tr>\r\n\r\n");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 484, 49, true);

            
            #line 26 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\IdfOnlyList.cshtml"
 foreach (var item in Model) {

            
            #line default
            #line hidden
BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 565, 24, true);

WriteLiteral("    <tr>\r\n        <td>\r\n");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 565, 24, true);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 589, 12, true);

WriteLiteral("            ");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 589, 12, true);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 602, 45, false);

            
            #line 29 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\IdfOnlyList.cshtml"
       Write(Html.DisplayFor(modelItem => item.IsNotFound));

            
            #line default
            #line hidden
EndContext("~/Views/IDF/IdfOnlyList.cshtml", 602, 45, false);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 647, 31, true);

WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 647, 31, true);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 678, 12, true);

WriteLiteral("            ");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 678, 12, true);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 691, 51, false);

            
            #line 32 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\IdfOnlyList.cshtml"
       Write(Html.DisplayFor(modelItem => item.ExceptionOccured));

            
            #line default
            #line hidden
EndContext("~/Views/IDF/IdfOnlyList.cshtml", 691, 51, false);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 742, 31, true);

WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 742, 31, true);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 773, 12, true);

WriteLiteral("            ");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 773, 12, true);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 786, 51, false);

            
            #line 35 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\IdfOnlyList.cshtml"
       Write(Html.DisplayFor(modelItem => item.ExceptionMessage));

            
            #line default
            #line hidden
EndContext("~/Views/IDF/IdfOnlyList.cshtml", 786, 51, false);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 837, 31, true);

WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 837, 31, true);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 868, 12, true);

WriteLiteral("            ");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 868, 12, true);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 881, 65, false);

            
            #line 38 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\IdfOnlyList.cshtml"
       Write(Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }));

            
            #line default
            #line hidden
EndContext("~/Views/IDF/IdfOnlyList.cshtml", 881, 65, false);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 946, 4, true);

WriteLiteral(" |\r\n");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 946, 4, true);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 950, 12, true);

WriteLiteral("            ");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 950, 12, true);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 963, 71, false);

            
            #line 39 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\IdfOnlyList.cshtml"
       Write(Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }));

            
            #line default
            #line hidden
EndContext("~/Views/IDF/IdfOnlyList.cshtml", 963, 71, false);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 1034, 4, true);

WriteLiteral(" |\r\n");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 1034, 4, true);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 1038, 12, true);

WriteLiteral("            ");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 1038, 12, true);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 1051, 69, false);

            
            #line 40 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\IdfOnlyList.cshtml"
       Write(Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ }));

            
            #line default
            #line hidden
EndContext("~/Views/IDF/IdfOnlyList.cshtml", 1051, 69, false);

BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 1120, 28, true);

WriteLiteral("\r\n        </td>\r\n    </tr>\r\n");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 1120, 28, true);

            
            #line 43 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\IdfOnlyList.cshtml"
}

            
            #line default
            #line hidden
BeginContext("~/Views/IDF/IdfOnlyList.cshtml", 1151, 12, true);

WriteLiteral("\r\n</table>\r\n");

EndContext("~/Views/IDF/IdfOnlyList.cshtml", 1151, 12, true);

        }
    }
}
