#pragma checksum "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\DriverMailer\DeliveryDriver.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "3A7747B0AD2E513035D723AAE966D72C753E6B65"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    
    
    public class _Page_Views_DriverMailer_DeliveryDriver_cshtml : System.Web.Mvc.WebViewPage<MvcChipRequest.ViewModels.AllChipRequestsViewModel> {
        
#line hidden
        
        public _Page_Views_DriverMailer_DeliveryDriver_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/DriverMailer/DeliveryDriver.cshtml", 61, 42, true);

WriteLiteral("\r\n<h1>IDF is ready for pickup</h1>\r\n\r\n<div");

EndContext("~/Views/DriverMailer/DeliveryDriver.cshtml", 61, 42, true);

BeginContext("~/Views/DriverMailer/DeliveryDriver.cshtml", 103, 34, true);

WriteLiteral(" class=\"hr hr-18 dotted hr-double\"");

EndContext("~/Views/DriverMailer/DeliveryDriver.cshtml", 103, 34, true);

BeginContext("~/Views/DriverMailer/DeliveryDriver.cshtml", 137, 9, true);

WriteLiteral("></div>\r\n");

EndContext("~/Views/DriverMailer/DeliveryDriver.cshtml", 137, 9, true);

BeginContext("~/Views/DriverMailer/DeliveryDriver.cshtml", 825, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/DriverMailer/DeliveryDriver.cshtml", 825, 2, true);

        }
    }
}
