#pragma checksum "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\ReleaseIDF.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "4457474CE165155F7438FBBE63573E808299A31B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    
    
    public class _Page_Views_IDF_ReleaseIDF_cshtml : System.Web.Mvc.WebViewPage<MvcChipRequest.ViewModels.AllChipRequestsViewModel> {
        
#line hidden
        
        public _Page_Views_IDF_ReleaseIDF_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 2 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\ReleaseIDF.cshtml"
  
    ViewBag.Title = "IDF Release List";

            
            #line default
            #line hidden
BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 105, 122, true);

WriteLiteral("\r\n<style>\r\n.td-one-line\r\n{\r\n  white-space:nowrap;\r\n  width:auto;\r\n  vertical-alig" +
"n:top;\r\n}\r\n\r\n</style>\r\n<div>IDF Number:  ");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 105, 122, true);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 228, 17, false);

            
            #line 14 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\ReleaseIDF.cshtml"
             Write(ViewBag.IdfNumber);

            
            #line default
            #line hidden
EndContext("~/Views/IDF/ReleaseIDF.cshtml", 228, 17, false);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 245, 12, true);

WriteLiteral("</div>\r\n<div");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 245, 12, true);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 257, 34, true);

WriteLiteral(" class=\"hr hr-18 dotted hr-double\"");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 257, 34, true);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 291, 13, true);

WriteLiteral("></div>\r\n<div");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 291, 13, true);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 304, 12, true);

WriteLiteral(" class=\"row\"");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 304, 12, true);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 316, 11, true);

WriteLiteral(">\r\n    <div");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 316, 11, true);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 327, 18, true);

WriteLiteral(" class=\"col-xs-12\"");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 327, 18, true);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 345, 15, true);

WriteLiteral(">\r\n        <div");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 345, 15, true);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 360, 24, true);

WriteLiteral(" class=\"table-resonsive\"");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 360, 24, true);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 384, 21, true);

WriteLiteral(">\r\n            <table");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 384, 21, true);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 405, 23, true);

WriteLiteral(" id=\"all-demands-table\"");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 405, 23, true);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 428, 55, true);

WriteLiteral(" class=\"table table-striped table-bordered table-hover\"");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 428, 55, true);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 483, 372, true);

WriteLiteral(@">
                <thead>
                    <tr>
                        <th>MCN</th>
                        <th>Release Date</th>
                        <th>Released By</th>
                        <th>Quantity</th>
                        <th>Notes</th>
                        
                    </tr>
                </thead>
                <tbody>
");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 483, 372, true);

            
            #line 31 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\ReleaseIDF.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 31 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\ReleaseIDF.cshtml"
                     foreach (var idf in Model.releases)
                    {

            
            #line default
            #line hidden
BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 936, 62, true);

WriteLiteral("                        <tr>\r\n                            <td>");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 936, 62, true);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 999, 35, false);

            
            #line 34 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\ReleaseIDF.cshtml"
                           Write(idf.ATP.Demand.ChipRequest.Chip.MCN);

            
            #line default
            #line hidden
EndContext("~/Views/IDF/ReleaseIDF.cshtml", 999, 35, false);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 1034, 39, true);

WriteLiteral("</td>\r\n                            <td>");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 1034, 39, true);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 1074, 15, false);

            
            #line 35 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\ReleaseIDF.cshtml"
                           Write(idf.ReleaseDate);

            
            #line default
            #line hidden
EndContext("~/Views/IDF/ReleaseIDF.cshtml", 1074, 15, false);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 1089, 39, true);

WriteLiteral("</td>\r\n                            <td>");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 1089, 39, true);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 1129, 14, false);

            
            #line 36 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\ReleaseIDF.cshtml"
                           Write(idf.ReleasedBy);

            
            #line default
            #line hidden
EndContext("~/Views/IDF/ReleaseIDF.cshtml", 1129, 14, false);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 1143, 39, true);

WriteLiteral("</td>\r\n                            <td>");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 1143, 39, true);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 1183, 12, false);

            
            #line 37 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\ReleaseIDF.cshtml"
                           Write(idf.Quantity);

            
            #line default
            #line hidden
EndContext("~/Views/IDF/ReleaseIDF.cshtml", 1183, 12, false);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 1195, 39, true);

WriteLiteral("</td>\r\n                            <td>");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 1195, 39, true);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 1235, 16, false);

            
            #line 38 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\ReleaseIDF.cshtml"
                           Write(idf.ReleaseNotes);

            
            #line default
            #line hidden
EndContext("~/Views/IDF/ReleaseIDF.cshtml", 1235, 16, false);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 1251, 38, true);

WriteLiteral("</td>\r\n                        </tr>\r\n");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 1251, 38, true);

            
            #line 40 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\ReleaseIDF.cshtml"
                    }

            
            #line default
            #line hidden
BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 1312, 90, true);

WriteLiteral("\r\n                </tbody>\r\n            </table>\r\n        </div>\r\n    </div>\r\n</d" +
"iv>\r\n<div");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 1312, 90, true);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 1402, 20, true);

WriteLiteral(" class=\"input-group\"");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 1402, 20, true);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 1422, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 1422, 3, true);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 1425, 4, true);

WriteLiteral("    ");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 1425, 4, true);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 1430, 117, false);

            
            #line 48 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\ReleaseIDF.cshtml"
Write(Html.RouteLink("Send Driver MSM Alert", new { controller = "IDF", action = "DriverMSMAlert", id = ViewBag.IdfNumber}));

            
            #line default
            #line hidden
EndContext("~/Views/IDF/ReleaseIDF.cshtml", 1430, 117, false);

BeginContext("~/Views/IDF/ReleaseIDF.cshtml", 1547, 14, true);

WriteLiteral("\r\n</div>\r\n\r\n\r\n");

EndContext("~/Views/IDF/ReleaseIDF.cshtml", 1547, 14, true);

        }
    }
}
