#pragma checksum "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "46EEFB3652133E59A2C400DB4C46C67AFD34ABF8"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    
    
    public class _Page_Views_ChipRequest_GTW_cshtml : System.Web.Mvc.WebViewPage<MvcChipRequest.ViewModels.AllChipRequestsViewModel> {
        
#line hidden
        
        public _Page_Views_ChipRequest_GTW_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 2 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml"
  
    ViewBag.Title = "GTW Demands";

            
            #line default
            #line hidden
BeginContext("~/Views/ChipRequest/GTW.cshtml", 100, 110, true);

WriteLiteral("\r\n<style>\r\n.td-one-line\r\n{\r\n  white-space:nowrap;\r\n  width:auto;\r\n  vertical-alig" +
"n:top;\r\n}\r\n\r\n</style>\r\n\r\n<div");

EndContext("~/Views/ChipRequest/GTW.cshtml", 100, 110, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 210, 34, true);

WriteLiteral(" class=\"hr hr-18 dotted hr-double\"");

EndContext("~/Views/ChipRequest/GTW.cshtml", 210, 34, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 244, 13, true);

WriteLiteral("></div>\r\n<div");

EndContext("~/Views/ChipRequest/GTW.cshtml", 244, 13, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 257, 12, true);

WriteLiteral(" class=\"row\"");

EndContext("~/Views/ChipRequest/GTW.cshtml", 257, 12, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 269, 11, true);

WriteLiteral(">\r\n    <div");

EndContext("~/Views/ChipRequest/GTW.cshtml", 269, 11, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 280, 18, true);

WriteLiteral(" class=\"col-xs-12\"");

EndContext("~/Views/ChipRequest/GTW.cshtml", 280, 18, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 298, 15, true);

WriteLiteral(">\r\n        <div");

EndContext("~/Views/ChipRequest/GTW.cshtml", 298, 15, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 313, 24, true);

WriteLiteral(" class=\"table-resonsive\"");

EndContext("~/Views/ChipRequest/GTW.cshtml", 313, 24, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 337, 21, true);

WriteLiteral(">\r\n            <table");

EndContext("~/Views/ChipRequest/GTW.cshtml", 337, 21, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 358, 23, true);

WriteLiteral(" id=\"all-demands-table\"");

EndContext("~/Views/ChipRequest/GTW.cshtml", 358, 23, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 381, 55, true);

WriteLiteral(" class=\"table table-striped table-bordered table-hover\"");

EndContext("~/Views/ChipRequest/GTW.cshtml", 381, 55, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 436, 232, true);

WriteLiteral(">\r\n                <thead>\r\n                    <tr>\r\n                        <th" +
">MCN</th>\r\n                        <th>Status</th>\r\n                        <th>" +
"PMPA</th>\r\n                        <th>\r\n                            <i");

EndContext("~/Views/ChipRequest/GTW.cshtml", 436, 232, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 668, 44, true);

WriteLiteral(" class=\"icon-calendar bigger-100 hidden-480\"");

EndContext("~/Views/ChipRequest/GTW.cshtml", 668, 44, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 712, 405, true);

WriteLiteral(@"></i>
                            Needed By
                        </th>
                        <th>Qty</th>
                        <th>ATP Total</th>
                        <th>ATP Delta</th>
                        <th>Open</th>
                        <th>Comments</th>
                        <th>Partial</th>
                    </tr>
                </thead>
                <tbody>
");

EndContext("~/Views/ChipRequest/GTW.cshtml", 712, 405, true);

            
            #line 38 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 38 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml"
                     foreach (var dm in Model.demands)
                    {

            
            #line default
            #line hidden
BeginContext("~/Views/ChipRequest/GTW.cshtml", 1196, 61, true);

WriteLiteral("                        <tr>\r\n                            <td");

EndContext("~/Views/ChipRequest/GTW.cshtml", 1196, 61, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1257, 20, true);

WriteLiteral(" class=\"td-one-line\"");

EndContext("~/Views/ChipRequest/GTW.cshtml", 1257, 20, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1277, 1, true);

WriteLiteral(">");

EndContext("~/Views/ChipRequest/GTW.cshtml", 1277, 1, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1279, 136, false);

            
            #line 41 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml"
                                               Write(Html.RouteLink(dm.ChipRequest.Chip.MCN, "Default", new { controller = "ChipRequest", action = "Edit", id = dm.ChipRequestID, dsid = 4 }));

            
            #line default
            #line hidden
EndContext("~/Views/ChipRequest/GTW.cshtml", 1279, 136, false);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1415, 39, true);

WriteLiteral("</td>\r\n                            <td>");

EndContext("~/Views/ChipRequest/GTW.cshtml", 1415, 39, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1455, 22, false);

            
            #line 42 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml"
                           Write(dm.DemandStatus.Status);

            
            #line default
            #line hidden
EndContext("~/Views/ChipRequest/GTW.cshtml", 1455, 22, false);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1477, 38, true);

WriteLiteral("</td>\r\n                            <td");

EndContext("~/Views/ChipRequest/GTW.cshtml", 1477, 38, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1515, 20, true);

WriteLiteral(" class=\"td-one-line\"");

EndContext("~/Views/ChipRequest/GTW.cshtml", 1515, 20, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1535, 1, true);

WriteLiteral(">");

EndContext("~/Views/ChipRequest/GTW.cshtml", 1535, 1, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1537, 7, false);

            
            #line 43 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml"
                                               Write(dm.PMPA);

            
            #line default
            #line hidden
EndContext("~/Views/ChipRequest/GTW.cshtml", 1537, 7, false);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1544, 38, true);

WriteLiteral("</td>\r\n                            <td");

EndContext("~/Views/ChipRequest/GTW.cshtml", 1544, 38, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1582, 20, true);

WriteLiteral(" class=\"td-one-line\"");

EndContext("~/Views/ChipRequest/GTW.cshtml", 1582, 20, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1602, 1, true);

WriteLiteral(">");

EndContext("~/Views/ChipRequest/GTW.cshtml", 1602, 1, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1604, 30, false);

            
            #line 44 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml"
                                               Write(dm.NeededBy.ToLongDateString());

            
            #line default
            #line hidden
EndContext("~/Views/ChipRequest/GTW.cshtml", 1604, 30, false);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1634, 39, true);

WriteLiteral("</td>\r\n                            <td>");

EndContext("~/Views/ChipRequest/GTW.cshtml", 1634, 39, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1674, 11, false);

            
            #line 45 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml"
                           Write(dm.Quantity);

            
            #line default
            #line hidden
EndContext("~/Views/ChipRequest/GTW.cshtml", 1674, 11, false);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1685, 39, true);

WriteLiteral("</td>\r\n                            <td>");

EndContext("~/Views/ChipRequest/GTW.cshtml", 1685, 39, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1725, 9, false);

            
            #line 46 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml"
                           Write(dm.ATPSum);

            
            #line default
            #line hidden
EndContext("~/Views/ChipRequest/GTW.cshtml", 1725, 9, false);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1734, 39, true);

WriteLiteral("</td>\r\n                            <td>");

EndContext("~/Views/ChipRequest/GTW.cshtml", 1734, 39, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1774, 11, false);

            
            #line 47 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml"
                           Write(dm.ATPDelta);

            
            #line default
            #line hidden
EndContext("~/Views/ChipRequest/GTW.cshtml", 1774, 11, false);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1785, 39, true);

WriteLiteral("</td>\r\n                            <td>");

EndContext("~/Views/ChipRequest/GTW.cshtml", 1785, 39, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1825, 13, false);

            
            #line 48 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml"
                           Write(dm.OpenDemand);

            
            #line default
            #line hidden
EndContext("~/Views/ChipRequest/GTW.cshtml", 1825, 13, false);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1838, 39, true);

WriteLiteral("</td>\r\n                            <td>");

EndContext("~/Views/ChipRequest/GTW.cshtml", 1838, 39, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1878, 11, false);

            
            #line 49 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml"
                           Write(dm.Comments);

            
            #line default
            #line hidden
EndContext("~/Views/ChipRequest/GTW.cshtml", 1878, 11, false);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1889, 39, true);

WriteLiteral("</td>\r\n                            <td>");

EndContext("~/Views/ChipRequest/GTW.cshtml", 1889, 39, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1929, 17, false);

            
            #line 50 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml"
                           Write(dm.PartialRelease);

            
            #line default
            #line hidden
EndContext("~/Views/ChipRequest/GTW.cshtml", 1929, 17, false);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 1946, 38, true);

WriteLiteral("</td>\r\n                        </tr>\r\n");

EndContext("~/Views/ChipRequest/GTW.cshtml", 1946, 38, true);

            
            #line 52 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml"
                    }

            
            #line default
            #line hidden
BeginContext("~/Views/ChipRequest/GTW.cshtml", 2007, 99, true);

WriteLiteral("\r\n                </tbody>\r\n            </table>\r\n        </div>\r\n    </div>\r\n</d" +
"iv>\r\n\r\n\r\n\r\n<script");

EndContext("~/Views/ChipRequest/GTW.cshtml", 2007, 99, true);

WriteAttribute("src", Tuple.Create(" src=\"", 2106), Tuple.Create("\"", 2156)
            
            #line 62 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml"
, Tuple.Create(Tuple.Create("", 2112), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/js/bootstrap.min.js")
            
            #line default
            #line hidden
, 2112), false)
);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 2157, 60, true);

WriteLiteral("></script>\r\n\r\n<!-- page specific plugin scripts -->\r\n<script");

EndContext("~/Views/ChipRequest/GTW.cshtml", 2157, 60, true);

WriteAttribute("src", Tuple.Create(" src=\"", 2217), Tuple.Create("\"", 2301)
            
            #line 65 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml"
, Tuple.Create(Tuple.Create("", 2223), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/js/DataTables-1.9.4/media/js/jquery.dataTables.min.js")
            
            #line default
            #line hidden
, 2223), false)
);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 2302, 19, true);

WriteLiteral("></script>\r\n<script");

EndContext("~/Views/ChipRequest/GTW.cshtml", 2302, 19, true);

WriteAttribute("src", Tuple.Create(" src=\"", 2321), Tuple.Create("\"", 2416)
            
            #line 66 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml"
, Tuple.Create(Tuple.Create("", 2327), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/js/DataTables-1.9.4/extras/TableTools/media/js/TableTools.min.js")
            
            #line default
            #line hidden
, 2327), false)
);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 2417, 19, true);

WriteLiteral("></script>\r\n<script");

EndContext("~/Views/ChipRequest/GTW.cshtml", 2417, 19, true);

WriteAttribute("src", Tuple.Create(" src=\"", 2436), Tuple.Create("\"", 2500)
            
            #line 67 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml"
, Tuple.Create(Tuple.Create("", 2442), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/js/jquery.dataTables.bootstrap.js")
            
            #line default
            #line hidden
, 2442), false)
);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 2501, 17, true);

WriteLiteral("></script>\r\n<link");

EndContext("~/Views/ChipRequest/GTW.cshtml", 2501, 17, true);

WriteAttribute("href", Tuple.Create(" href=\"", 2518), Tuple.Create("\"", 2610)
            
            #line 68 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml"
, Tuple.Create(Tuple.Create("", 2525), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/DataTables-1.9.4/extras/TableTools/media/css/TableTools.css")
            
            #line default
            #line hidden
, 2525), false)
);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 2611, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/ChipRequest/GTW.cshtml", 2611, 17, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 2628, 38, true);

WriteLiteral(" />\r\n\r\n<!-- ace scripts -->\r\n\r\n<script");

EndContext("~/Views/ChipRequest/GTW.cshtml", 2628, 38, true);

WriteAttribute("src", Tuple.Create(" src=\"", 2666), Tuple.Create("\"", 2719)
            
            #line 72 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml"
, Tuple.Create(Tuple.Create("", 2672), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/js/ace-elements.min.js")
            
            #line default
            #line hidden
, 2672), false)
);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 2720, 19, true);

WriteLiteral("></script>\r\n<script");

EndContext("~/Views/ChipRequest/GTW.cshtml", 2720, 19, true);

WriteAttribute("src", Tuple.Create(" src=\"", 2739), Tuple.Create("\"", 2783)
            
            #line 73 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml"
, Tuple.Create(Tuple.Create("", 2745), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/js/ace.min.js")
            
            #line default
            #line hidden
, 2745), false)
);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 2784, 556, true);

WriteLiteral(@"></script>



<script>
    $(document).ready(function () {
        $('#all-demands-table').dataTable({
            ""sDom"": 'T<""clear"">lfrtip',
            ""oTableTools"": {
                ""aButtons"": [
                    {
                        ""sExtends"": ""csv"",
                        ""sButtonText"": ""Save to CSV File""
                    },
                    {
                        ""sExtends"": ""print"",
                        ""sButtonText"": ""Print View""
                    }
                ],
                ""sSwfPath"": """);

EndContext("~/Views/ChipRequest/GTW.cshtml", 2784, 556, true);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 3341, 90, false);

            
            #line 92 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\ChipRequest\GTW.cshtml"
                        Write(Url.Content("~/Content/DataTables-1.9.4/extras/TableTools/media/swf/copy_csv_xls_pdf.swf"));

            
            #line default
            #line hidden
EndContext("~/Views/ChipRequest/GTW.cshtml", 3341, 90, false);

BeginContext("~/Views/ChipRequest/GTW.cshtml", 3431, 201, true);

WriteLiteral("\",\r\n            },\r\n            \"iDisplayLength\": 50,\r\n            \"aLengthMenu\":" +
" [[10, 25, 50, 100, -1], [10, 25, 50, 100, \"All\"]],\r\n            \"bStateSave\": t" +
"rue\r\n        });\r\n\r\n    });\r\n</script>\r\n");

EndContext("~/Views/ChipRequest/GTW.cshtml", 3431, 201, true);

        }
    }
}
