#pragma checksum "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\Shared\Error.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "AB3621667AAC175B23DBCA4931EE41A0D483C537"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    
    
    public class _Page_Views_Shared_Error_cshtml : System.Web.Mvc.WebViewPage<System.Web.Mvc.HandleErrorInfo> {
        
#line hidden
        
        public _Page_Views_Shared_Error_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\Shared\Error.cshtml"
  
    ViewBag.Title = "Error";

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/Error.cshtml", 76, 11, true);

WriteLiteral("\r\n\r\n<hgroup");

EndContext("~/Views/Shared/Error.cshtml", 76, 11, true);

BeginContext("~/Views/Shared/Error.cshtml", 87, 14, true);

WriteLiteral(" class=\"title\"");

EndContext("~/Views/Shared/Error.cshtml", 87, 14, true);

BeginContext("~/Views/Shared/Error.cshtml", 101, 10, true);

WriteLiteral(">\r\n    <h1");

EndContext("~/Views/Shared/Error.cshtml", 101, 10, true);

BeginContext("~/Views/Shared/Error.cshtml", 111, 14, true);

WriteLiteral(" class=\"error\"");

EndContext("~/Views/Shared/Error.cshtml", 111, 14, true);

BeginContext("~/Views/Shared/Error.cshtml", 125, 21, true);

WriteLiteral(">Error.</h1>\r\n    <h2");

EndContext("~/Views/Shared/Error.cshtml", 125, 21, true);

BeginContext("~/Views/Shared/Error.cshtml", 146, 14, true);

WriteLiteral(" class=\"error\"");

EndContext("~/Views/Shared/Error.cshtml", 146, 14, true);

BeginContext("~/Views/Shared/Error.cshtml", 160, 67, true);

WriteLiteral(">An error occurred while processing your request.</h2>\r\n</hgroup>\r\n");

EndContext("~/Views/Shared/Error.cshtml", 160, 67, true);

        }
    }
}
