#pragma checksum "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "7D12238733CD5E4AD24C52B048EF7B1ECB600427"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    
    
    public class _Page_Views_IDF_Index_cshtml : System.Web.Mvc.WebViewPage<MvcChipRequest.ViewModels.AllChipRequestsViewModel> {
        
#line hidden
        
        public _Page_Views_IDF_Index_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 2 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\Index.cshtml"
  
    ViewBag.Title = "IDF Index List";

            
            #line default
            #line hidden
BeginContext("~/Views/IDF/Index.cshtml", 103, 110, true);

WriteLiteral("\r\n<style>\r\n.td-one-line\r\n{\r\n  white-space:nowrap;\r\n  width:auto;\r\n  vertical-alig" +
"n:top;\r\n}\r\n\r\n</style>\r\n\r\n<div");

EndContext("~/Views/IDF/Index.cshtml", 103, 110, true);

BeginContext("~/Views/IDF/Index.cshtml", 213, 34, true);

WriteLiteral(" class=\"hr hr-18 dotted hr-double\"");

EndContext("~/Views/IDF/Index.cshtml", 213, 34, true);

BeginContext("~/Views/IDF/Index.cshtml", 247, 13, true);

WriteLiteral("></div>\r\n<div");

EndContext("~/Views/IDF/Index.cshtml", 247, 13, true);

BeginContext("~/Views/IDF/Index.cshtml", 260, 12, true);

WriteLiteral(" class=\"row\"");

EndContext("~/Views/IDF/Index.cshtml", 260, 12, true);

BeginContext("~/Views/IDF/Index.cshtml", 272, 11, true);

WriteLiteral(">\r\n    <div");

EndContext("~/Views/IDF/Index.cshtml", 272, 11, true);

BeginContext("~/Views/IDF/Index.cshtml", 283, 18, true);

WriteLiteral(" class=\"col-xs-12\"");

EndContext("~/Views/IDF/Index.cshtml", 283, 18, true);

BeginContext("~/Views/IDF/Index.cshtml", 301, 15, true);

WriteLiteral(">\r\n        <div");

EndContext("~/Views/IDF/Index.cshtml", 301, 15, true);

BeginContext("~/Views/IDF/Index.cshtml", 316, 24, true);

WriteLiteral(" class=\"table-resonsive\"");

EndContext("~/Views/IDF/Index.cshtml", 316, 24, true);

BeginContext("~/Views/IDF/Index.cshtml", 340, 21, true);

WriteLiteral(">\r\n            <table");

EndContext("~/Views/IDF/Index.cshtml", 340, 21, true);

BeginContext("~/Views/IDF/Index.cshtml", 361, 23, true);

WriteLiteral(" id=\"all-demands-table\"");

EndContext("~/Views/IDF/Index.cshtml", 361, 23, true);

BeginContext("~/Views/IDF/Index.cshtml", 384, 55, true);

WriteLiteral(" class=\"table table-striped table-bordered table-hover\"");

EndContext("~/Views/IDF/Index.cshtml", 384, 55, true);

BeginContext("~/Views/IDF/Index.cshtml", 439, 481, true);

WriteLiteral(@">
                <thead>
                    <tr>
                        <th>Release ID</th>
                        <th>MCN</th>
                        <th>IDF Number</th>
                        <th>Release Date</th>
                        <th>Released By</th>
                        <th>Quantity</th>
                        <th>Notes</th>
                        <th>Email Sent</th>
                    </tr>
                </thead>
                <tbody>
");

EndContext("~/Views/IDF/Index.cshtml", 439, 481, true);

            
            #line 33 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 33 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\Index.cshtml"
                     foreach (var idf in Model.releases)
                    {

            
            #line default
            #line hidden
BeginContext("~/Views/IDF/Index.cshtml", 1001, 62, true);

WriteLiteral("                        <tr>\r\n                            <td>");

EndContext("~/Views/IDF/Index.cshtml", 1001, 62, true);

BeginContext("~/Views/IDF/Index.cshtml", 1064, 13, false);

            
            #line 36 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\Index.cshtml"
                           Write(idf.ReleaseID);

            
            #line default
            #line hidden
EndContext("~/Views/IDF/Index.cshtml", 1064, 13, false);

BeginContext("~/Views/IDF/Index.cshtml", 1077, 39, true);

WriteLiteral("</td>\r\n                            <td>");

EndContext("~/Views/IDF/Index.cshtml", 1077, 39, true);

BeginContext("~/Views/IDF/Index.cshtml", 1117, 35, false);

            
            #line 37 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\Index.cshtml"
                           Write(idf.ATP.Demand.ChipRequest.Chip.MCN);

            
            #line default
            #line hidden
EndContext("~/Views/IDF/Index.cshtml", 1117, 35, false);

BeginContext("~/Views/IDF/Index.cshtml", 1152, 39, true);

WriteLiteral("</td>\r\n                            <td>");

EndContext("~/Views/IDF/Index.cshtml", 1152, 39, true);

BeginContext("~/Views/IDF/Index.cshtml", 1192, 98, false);

            
            #line 38 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\Index.cshtml"
                           Write(Html.RouteLink(idf.IDF, "Default", new { controller = "IDF", action = "ReleaseIDF", id = idf.IDF}));

            
            #line default
            #line hidden
EndContext("~/Views/IDF/Index.cshtml", 1192, 98, false);

BeginContext("~/Views/IDF/Index.cshtml", 1290, 39, true);

WriteLiteral("</td>\r\n                            <td>");

EndContext("~/Views/IDF/Index.cshtml", 1290, 39, true);

BeginContext("~/Views/IDF/Index.cshtml", 1330, 15, false);

            
            #line 39 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\Index.cshtml"
                           Write(idf.ReleaseDate);

            
            #line default
            #line hidden
EndContext("~/Views/IDF/Index.cshtml", 1330, 15, false);

BeginContext("~/Views/IDF/Index.cshtml", 1345, 39, true);

WriteLiteral("</td>\r\n                            <td>");

EndContext("~/Views/IDF/Index.cshtml", 1345, 39, true);

BeginContext("~/Views/IDF/Index.cshtml", 1385, 14, false);

            
            #line 40 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\Index.cshtml"
                           Write(idf.ReleasedBy);

            
            #line default
            #line hidden
EndContext("~/Views/IDF/Index.cshtml", 1385, 14, false);

BeginContext("~/Views/IDF/Index.cshtml", 1399, 39, true);

WriteLiteral("</td>\r\n                            <td>");

EndContext("~/Views/IDF/Index.cshtml", 1399, 39, true);

BeginContext("~/Views/IDF/Index.cshtml", 1439, 12, false);

            
            #line 41 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\Index.cshtml"
                           Write(idf.Quantity);

            
            #line default
            #line hidden
EndContext("~/Views/IDF/Index.cshtml", 1439, 12, false);

BeginContext("~/Views/IDF/Index.cshtml", 1451, 39, true);

WriteLiteral("</td>\r\n                            <td>");

EndContext("~/Views/IDF/Index.cshtml", 1451, 39, true);

BeginContext("~/Views/IDF/Index.cshtml", 1491, 16, false);

            
            #line 42 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\Index.cshtml"
                           Write(idf.ReleaseNotes);

            
            #line default
            #line hidden
EndContext("~/Views/IDF/Index.cshtml", 1491, 16, false);

BeginContext("~/Views/IDF/Index.cshtml", 1507, 39, true);

WriteLiteral("</td>\r\n                            <td>");

EndContext("~/Views/IDF/Index.cshtml", 1507, 39, true);

BeginContext("~/Views/IDF/Index.cshtml", 1547, 13, false);

            
            #line 43 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\Index.cshtml"
                           Write(idf.EmailSent);

            
            #line default
            #line hidden
EndContext("~/Views/IDF/Index.cshtml", 1547, 13, false);

BeginContext("~/Views/IDF/Index.cshtml", 1560, 38, true);

WriteLiteral("</td>\r\n                        </tr>\r\n");

EndContext("~/Views/IDF/Index.cshtml", 1560, 38, true);

            
            #line 45 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\IDF\Index.cshtml"
                    }

            
            #line default
            #line hidden
BeginContext("~/Views/IDF/Index.cshtml", 1621, 92, true);

WriteLiteral("\r\n                </tbody>\r\n            </table>\r\n        </div>\r\n    </div>\r\n</d" +
"iv>\r\n\r\n\r\n\r\n");

EndContext("~/Views/IDF/Index.cshtml", 1621, 92, true);

        }
    }
}
