#pragma checksum "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\Shared\_Layout.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "FFCFF18971BCB0330C98B899270DA61CD5357EC4"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    
    
    public class _Page_Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Shared__Layout_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/Shared/_Layout.cshtml", 0, 22, true);

WriteLiteral("<!DOCTYPE html>\r\n<html");

EndContext("~/Views/Shared/_Layout.cshtml", 0, 22, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 22, 10, true);

WriteLiteral(" lang=\"en\"");

EndContext("~/Views/Shared/_Layout.cshtml", 22, 10, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 32, 20, true);

WriteLiteral(">\r\n<head>\r\n    <meta");

EndContext("~/Views/Shared/_Layout.cshtml", 32, 20, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 52, 16, true);

WriteLiteral(" charset=\"utf-8\"");

EndContext("~/Views/Shared/_Layout.cshtml", 52, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 68, 59, true);

WriteLiteral(" />\r\n    <title>Active - Chip Requests</title>\r\n\r\n    <meta");

EndContext("~/Views/Shared/_Layout.cshtml", 68, 59, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 127, 19, true);

WriteLiteral(" name=\"description\"");

EndContext("~/Views/Shared/_Layout.cshtml", 127, 19, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 146, 31, true);

WriteLiteral(" content=\"Active Chip Requests\"");

EndContext("~/Views/Shared/_Layout.cshtml", 146, 31, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 177, 14, true);

WriteLiteral(" />\r\n    <meta");

EndContext("~/Views/Shared/_Layout.cshtml", 177, 14, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 191, 16, true);

WriteLiteral(" name=\"viewport\"");

EndContext("~/Views/Shared/_Layout.cshtml", 191, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 207, 48, true);

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

EndContext("~/Views/Shared/_Layout.cshtml", 207, 48, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 255, 47, true);

WriteLiteral(" />\r\n\r\n    <!-- basic styles -->\r\n\r\n\r\n    <link");

EndContext("~/Views/Shared/_Layout.cshtml", 255, 47, true);

WriteAttribute("href", Tuple.Create(" href=\"", 302), Tuple.Create("\"", 355)
            
            #line 13 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 309), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/css/bootstrap.min.css")
            
            #line default
            #line hidden
, 309), false)
);

BeginContext("~/Views/Shared/_Layout.cshtml", 356, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/Shared/_Layout.cshtml", 356, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 373, 14, true);

WriteLiteral(" />\r\n    <link");

EndContext("~/Views/Shared/_Layout.cshtml", 373, 14, true);

WriteAttribute("href", Tuple.Create(" href=\"", 387), Tuple.Create("\"", 443)
            
            #line 14 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 394), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/css/font-awesome.min.css")
            
            #line default
            #line hidden
, 394), false)
);

BeginContext("~/Views/Shared/_Layout.cshtml", 444, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/Shared/_Layout.cshtml", 444, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 461, 82, true);

WriteLiteral(" />\r\n\r\n    <!-- page specific plugin styles -->\r\n\r\n    <!-- fonts -->\r\n\r\n    <lin" +
"k");

EndContext("~/Views/Shared/_Layout.cshtml", 461, 82, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 543, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/Shared/_Layout.cshtml", 543, 17, true);

WriteAttribute("href", Tuple.Create(" href=\"", 560), Tuple.Create("\"", 609)
            
            #line 20 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 567), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/css/ace-fonts.css")
            
            #line default
            #line hidden
, 567), false)
);

BeginContext("~/Views/Shared/_Layout.cshtml", 610, 43, true);

WriteLiteral(" />\r\n\r\n    <!-- ace styles -->\r\n\r\n    <link");

EndContext("~/Views/Shared/_Layout.cshtml", 610, 43, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 653, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/Shared/_Layout.cshtml", 653, 17, true);

WriteAttribute("href", Tuple.Create(" href=\"", 670), Tuple.Create("\"", 717)
            
            #line 24 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 677), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/css/ace.min.css")
            
            #line default
            #line hidden
, 677), false)
);

BeginContext("~/Views/Shared/_Layout.cshtml", 718, 14, true);

WriteLiteral(" />\r\n    <link");

EndContext("~/Views/Shared/_Layout.cshtml", 718, 14, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 732, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/Shared/_Layout.cshtml", 732, 17, true);

WriteAttribute("href", Tuple.Create(" href=\"", 749), Tuple.Create("\"", 800)
            
            #line 25 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 756), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/css/ace-rtl.min.css")
            
            #line default
            #line hidden
, 756), false)
);

BeginContext("~/Views/Shared/_Layout.cshtml", 801, 14, true);

WriteLiteral(" />\r\n    <link");

EndContext("~/Views/Shared/_Layout.cshtml", 801, 14, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 815, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/Shared/_Layout.cshtml", 815, 17, true);

WriteAttribute("href", Tuple.Create(" href=\"", 832), Tuple.Create("\"", 885)
            
            #line 26 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 839), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/css/ace-skins.min.css")
            
            #line default
            #line hidden
, 839), false)
);

BeginContext("~/Views/Shared/_Layout.cshtml", 886, 104, true);

WriteLiteral(" />\r\n\r\n    <!-- inline styles related to this page -->\r\n\r\n    <!-- ace settings h" +
"andler -->\r\n    <script");

EndContext("~/Views/Shared/_Layout.cshtml", 886, 104, true);

WriteAttribute("src", Tuple.Create(" src=\"", 990), Tuple.Create("\"", 1043)
            
            #line 31 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 996), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/js/jquery-2.1.0.min.js")
            
            #line default
            #line hidden
, 996), false)
);

BeginContext("~/Views/Shared/_Layout.cshtml", 1044, 23, true);

WriteLiteral("></script>\r\n    <script");

EndContext("~/Views/Shared/_Layout.cshtml", 1044, 23, true);

WriteAttribute("src", Tuple.Create(" src=\"", 1067), Tuple.Create("\"", 1117)
            
            #line 32 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1073), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/js/ace-extra.min.js")
            
            #line default
            #line hidden
, 1073), false)
);

BeginContext("~/Views/Shared/_Layout.cshtml", 1118, 53, true);

WriteLiteral("></script>\r\n\r\n    <!-- Select 2 Styles -->\r\n    <link");

EndContext("~/Views/Shared/_Layout.cshtml", 1118, 53, true);

WriteAttribute("href", Tuple.Create(" href=\"", 1171), Tuple.Create("\"", 1203)
, Tuple.Create(Tuple.Create("", 1178), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/select2.css")
, 1178), false)
);

BeginContext("~/Views/Shared/_Layout.cshtml", 1204, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1204, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1221, 15, true);

WriteLiteral(" />\r\n    <style");

EndContext("~/Views/Shared/_Layout.cshtml", 1221, 15, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1236, 16, true);

WriteLiteral(" type=\"text/css\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1236, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1252, 167, true);

WriteLiteral(">\r\n        .select2-container-multi .select2-choices .select2-search-field input " +
"{\r\n            height: auto;\r\n        }\r\n\r\n    </style>\r\n\r\n</head>\r\n\r\n<body>\r\n  " +
"  <div");

EndContext("~/Views/Shared/_Layout.cshtml", 1252, 167, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1419, 30, true);

WriteLiteral(" class=\"navbar navbar-default\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1419, 30, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1449, 12, true);

WriteLiteral(" id=\"navbar\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1449, 12, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1461, 18, true);

WriteLiteral(">\r\n        <script");

EndContext("~/Views/Shared/_Layout.cshtml", 1461, 18, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1479, 23, true);

WriteLiteral(" type=\"text/javascript\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1479, 23, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1502, 109, true);

WriteLiteral(">\r\n            try { ace.settings.check(\'navbar\', \'fixed\') } catch (e) { }\r\n     " +
"   </script>\r\n\r\n        <div");

EndContext("~/Views/Shared/_Layout.cshtml", 1502, 109, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1611, 25, true);

WriteLiteral(" class=\"navbar-container\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1611, 25, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1636, 22, true);

WriteLiteral(" id=\"navbar-container\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1636, 22, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1658, 19, true);

WriteLiteral(">\r\n            <div");

EndContext("~/Views/Shared/_Layout.cshtml", 1658, 19, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1677, 32, true);

WriteLiteral(" class=\"navbar-header pull-left\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1677, 32, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1709, 21, true);

WriteLiteral(">\r\n                <a");

EndContext("~/Views/Shared/_Layout.cshtml", 1709, 21, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1730, 62, true);

WriteLiteral(" href=\"http://mvcchiprequest-dev.qualcomm.com/MvcChipRequest/\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1730, 62, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1792, 21, true);

WriteLiteral(" class=\"navbar-brand\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1792, 21, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1813, 58, true);

WriteLiteral(">\r\n                    <small>\r\n                        <i");

EndContext("~/Views/Shared/_Layout.cshtml", 1813, 58, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1871, 18, true);

WriteLiteral(" class=\"icon-leaf\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1871, 18, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1889, 145, true);

WriteLiteral("></i>\r\n                        The Chip Request - Development Environment\r\n      " +
"              </small>\r\n                </a>\r\n                <a");

EndContext("~/Views/Shared/_Layout.cshtml", 1889, 145, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2034, 45, true);

WriteLiteral(" href=\"mailto:ops.it.issues@qti.qualcomm.com\"");

EndContext("~/Views/Shared/_Layout.cshtml", 2034, 45, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2079, 21, true);

WriteLiteral(" class=\"navbar-brand\"");

EndContext("~/Views/Shared/_Layout.cshtml", 2079, 21, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2100, 167, true);

WriteLiteral(">Click here to to request support for this web site</a>\r\n                <!-- /.b" +
"rand -->\r\n            </div>\r\n            <!-- /.navbar-header -->\r\n\r\n          " +
"  <div");

EndContext("~/Views/Shared/_Layout.cshtml", 2100, 167, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2267, 33, true);

WriteLiteral(" class=\"navbar-header pull-right\"");

EndContext("~/Views/Shared/_Layout.cshtml", 2267, 33, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2300, 18, true);

WriteLiteral(" role=\"navigation\"");

EndContext("~/Views/Shared/_Layout.cshtml", 2300, 18, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2318, 22, true);

WriteLiteral(">\r\n                <ul");

EndContext("~/Views/Shared/_Layout.cshtml", 2318, 22, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2340, 20, true);

WriteLiteral(" class=\"nav ace-nav\"");

EndContext("~/Views/Shared/_Layout.cshtml", 2340, 20, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2360, 26, true);

WriteLiteral(">\r\n                    <li");

EndContext("~/Views/Shared/_Layout.cshtml", 2360, 26, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2386, 19, true);

WriteLiteral(" class=\"light-blue\"");

EndContext("~/Views/Shared/_Layout.cshtml", 2386, 19, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2405, 65, true);

WriteLiteral(">\r\n                        <a>\r\n                            <span");

EndContext("~/Views/Shared/_Layout.cshtml", 2405, 65, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2470, 18, true);

WriteLiteral(" class=\"user-info\"");

EndContext("~/Views/Shared/_Layout.cshtml", 2470, 18, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2488, 60, true);

WriteLiteral(">\r\n                                <small>Welcome,</small>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 2488, 60, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2548, 32, true);

WriteLiteral("                                ");

EndContext("~/Views/Shared/_Layout.cshtml", 2548, 32, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2581, 18, false);

            
            #line 70 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\Shared\_Layout.cshtml"
                           Write(User.Identity.Name);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 2581, 18, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 2599, 281, true);

WriteLiteral(@"
                            </span>
                        </a>
                    </li>
                </ul>
                <!-- /.ace-nav -->
            </div>
            <!-- /.navbar-header -->
        </div>
        <!-- /.container -->
    </div>

    <div");

EndContext("~/Views/Shared/_Layout.cshtml", 2599, 281, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2880, 23, true);

WriteLiteral(" class=\"main-container\"");

EndContext("~/Views/Shared/_Layout.cshtml", 2880, 23, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2903, 20, true);

WriteLiteral(" id=\"main-container\"");

EndContext("~/Views/Shared/_Layout.cshtml", 2903, 20, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2923, 20, true);

WriteLiteral(">\r\n\r\n        <script");

EndContext("~/Views/Shared/_Layout.cshtml", 2923, 20, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2943, 23, true);

WriteLiteral(" type=\"text/javascript\"");

EndContext("~/Views/Shared/_Layout.cshtml", 2943, 23, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2966, 117, true);

WriteLiteral(">\r\n            try { ace.settings.check(\'main-container\', \'fixed\') } catch (e) { " +
"}\r\n        </script>\r\n\r\n        <div");

EndContext("~/Views/Shared/_Layout.cshtml", 2966, 117, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3083, 29, true);

WriteLiteral(" class=\"main-container-inner\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3083, 29, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3112, 17, true);

WriteLiteral(">\r\n            <a");

EndContext("~/Views/Shared/_Layout.cshtml", 3112, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3129, 21, true);

WriteLiteral(" class=\"menu-toggler\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3129, 21, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3150, 18, true);

WriteLiteral(" id=\"menu-toggler\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3150, 18, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3168, 9, true);

WriteLiteral(" href=\"#\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3168, 9, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3177, 24, true);

WriteLiteral(">\r\n                <span");

EndContext("~/Views/Shared/_Layout.cshtml", 3177, 24, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3201, 18, true);

WriteLiteral(" class=\"menu-text\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3201, 18, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3219, 46, true);

WriteLiteral("></span>\r\n            </a>\r\n\r\n            <div");

EndContext("~/Views/Shared/_Layout.cshtml", 3219, 46, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3265, 16, true);

WriteLiteral(" class=\"sidebar\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3265, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3281, 13, true);

WriteLiteral(" id=\"sidebar\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3281, 13, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3294, 26, true);

WriteLiteral(">\r\n                <script");

EndContext("~/Views/Shared/_Layout.cshtml", 3294, 26, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3320, 23, true);

WriteLiteral(" type=\"text/javascript\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3320, 23, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3343, 134, true);

WriteLiteral(">\r\n                    try { ace.settings.check(\'sidebar\', \'fixed\') } catch (e) {" +
" }\r\n                </script>\r\n\r\n                <div");

EndContext("~/Views/Shared/_Layout.cshtml", 3343, 134, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3477, 26, true);

WriteLiteral(" class=\"sidebar-shortcuts\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3477, 26, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3503, 23, true);

WriteLiteral(" id=\"sidebar-shortcuts\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3503, 23, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3526, 27, true);

WriteLiteral(">\r\n                    <div");

EndContext("~/Views/Shared/_Layout.cshtml", 3526, 27, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3553, 32, true);

WriteLiteral(" class=\"sidebar-shortcuts-large\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3553, 32, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3585, 29, true);

WriteLiteral(" id=\"sidebar-shortcuts-large\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3585, 29, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3614, 36, true);

WriteLiteral(">\r\n\r\n                        <button");

EndContext("~/Views/Shared/_Layout.cshtml", 3614, 36, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3650, 24, true);

WriteLiteral(" class=\"btn btn-success\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3650, 24, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3674, 93, true);

WriteLiteral(" onclick=\"window.open(&quot;http://mvcchiprequest-dev.qualcomm.com/MvcChipRequest" +
"/GTW&quot;)\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3674, 93, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3767, 33, true);

WriteLiteral(">\r\n                            <i");

EndContext("~/Views/Shared/_Layout.cshtml", 3767, 33, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3800, 30, true);

WriteLiteral(" class=\"icon-exclamation-sign\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3800, 30, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3830, 73, true);

WriteLiteral("></i>\r\n                        </button>\r\n                        <button");

EndContext("~/Views/Shared/_Layout.cshtml", 3830, 73, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3903, 21, true);

WriteLiteral(" class=\"btn btn-info\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3903, 21, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3924, 96, true);

WriteLiteral(" onclick=\"window.open(&quot;http://mvcchiprequest-dev.qualcomm.com/MvcChipRequest" +
"/Active&quot;)\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3924, 96, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4020, 33, true);

WriteLiteral(">\r\n                            <i");

EndContext("~/Views/Shared/_Layout.cshtml", 4020, 33, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4053, 22, true);

WriteLiteral(" class=\"icon-asterisk\"");

EndContext("~/Views/Shared/_Layout.cshtml", 4053, 22, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4075, 75, true);

WriteLiteral("></i>\r\n                        </button>\r\n\r\n                        <button");

EndContext("~/Views/Shared/_Layout.cshtml", 4075, 75, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4150, 24, true);

WriteLiteral(" class=\"btn btn-warning\"");

EndContext("~/Views/Shared/_Layout.cshtml", 4150, 24, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4174, 107, true);

WriteLiteral(" onclick=\"window.open(&quot;http://mvcchiprequest-dev.qualcomm.com/MvcChipRequest" +
"/Home/InActiveList&quot;)\"");

EndContext("~/Views/Shared/_Layout.cshtml", 4174, 107, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4281, 33, true);

WriteLiteral(">\r\n                            <i");

EndContext("~/Views/Shared/_Layout.cshtml", 4281, 33, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4314, 23, true);

WriteLiteral(" class=\"icon-thumbs-up\"");

EndContext("~/Views/Shared/_Layout.cshtml", 4314, 23, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4337, 75, true);

WriteLiteral("></i>\r\n                        </button>\r\n\r\n                        <button");

EndContext("~/Views/Shared/_Layout.cshtml", 4337, 75, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4412, 23, true);

WriteLiteral(" class=\"btn btn-danger\"");

EndContext("~/Views/Shared/_Layout.cshtml", 4412, 23, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4435, 94, true);

WriteLiteral(" onclick=\"window.open(&quot;http://mvcchiprequest-dev.qualcomm.com/MvcChipRequest" +
"/Chip&quot;)\"");

EndContext("~/Views/Shared/_Layout.cshtml", 4435, 94, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4529, 33, true);

WriteLiteral(">\r\n                            <i");

EndContext("~/Views/Shared/_Layout.cshtml", 4529, 33, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4562, 20, true);

WriteLiteral(" class=\"icon-wrench\"");

EndContext("~/Views/Shared/_Layout.cshtml", 4562, 20, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4582, 96, true);

WriteLiteral("></i>\r\n                        </button>\r\n                    </div>\r\n\r\n         " +
"           <div");

EndContext("~/Views/Shared/_Layout.cshtml", 4582, 96, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4678, 31, true);

WriteLiteral(" class=\"sidebar-shortcuts-mini\"");

EndContext("~/Views/Shared/_Layout.cshtml", 4678, 31, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4709, 28, true);

WriteLiteral(" id=\"sidebar-shortcuts-mini\"");

EndContext("~/Views/Shared/_Layout.cshtml", 4709, 28, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4737, 32, true);

WriteLiteral(">\r\n                        <span");

EndContext("~/Views/Shared/_Layout.cshtml", 4737, 32, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4769, 24, true);

WriteLiteral(" class=\"btn btn-success\"");

EndContext("~/Views/Shared/_Layout.cshtml", 4769, 24, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4793, 41, true);

WriteLiteral("></span>\r\n\r\n                        <span");

EndContext("~/Views/Shared/_Layout.cshtml", 4793, 41, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4834, 21, true);

WriteLiteral(" class=\"btn btn-info\"");

EndContext("~/Views/Shared/_Layout.cshtml", 4834, 21, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4855, 41, true);

WriteLiteral("></span>\r\n\r\n                        <span");

EndContext("~/Views/Shared/_Layout.cshtml", 4855, 41, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4896, 24, true);

WriteLiteral(" class=\"btn btn-warning\"");

EndContext("~/Views/Shared/_Layout.cshtml", 4896, 24, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4920, 41, true);

WriteLiteral("></span>\r\n\r\n                        <span");

EndContext("~/Views/Shared/_Layout.cshtml", 4920, 41, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4961, 23, true);

WriteLiteral(" class=\"btn btn-danger\"");

EndContext("~/Views/Shared/_Layout.cshtml", 4961, 23, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4984, 128, true);

WriteLiteral("></span>\r\n                    </div>\r\n                </div>\r\n                <!-" +
"- #sidebar-shortcuts -->\r\n\r\n                <ul");

EndContext("~/Views/Shared/_Layout.cshtml", 4984, 128, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 5112, 21, true);

WriteLiteral(" class=\"nav nav-list\"");

EndContext("~/Views/Shared/_Layout.cshtml", 5112, 21, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 5133, 29, true);

WriteLiteral(">\r\n                    <li>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 5133, 29, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 5162, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Shared/_Layout.cshtml", 5162, 24, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 5187, 88, false);

            
            #line 131 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\Shared\_Layout.cshtml"
                   Write(Html.RouteLink("Get to Work", "GTW", new { controller = "ChipRequest", action = "GTW" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 5187, 88, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 5275, 59, true);

WriteLiteral("  \r\n                    </li>\r\n\r\n                    <li>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 5275, 59, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 5334, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Shared/_Layout.cshtml", 5334, 24, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 5359, 82, false);

            
            #line 135 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\Shared\_Layout.cshtml"
                   Write(Html.RouteLink("Active", "active", new { controller = "Home", action = "Active" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 5359, 82, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 5441, 57, true);

WriteLiteral("\r\n                    </li>\r\n\r\n                    <li>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 5441, 57, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 5498, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Shared/_Layout.cshtml", 5498, 24, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 5523, 66, false);

            
            #line 139 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\Shared\_Layout.cshtml"
                   Write(Html.ActionLink("Fulfilled Chip Requests", "InActiveList", "Home"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 5523, 66, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 5589, 55, true);

WriteLiteral("\r\n                    </li>\r\n                    <li>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 5589, 55, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 5644, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Shared/_Layout.cshtml", 5644, 24, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 5669, 44, false);

            
            #line 142 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\Shared\_Layout.cshtml"
                   Write(Html.ActionLink("IDF Index", "Index", "IDF"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 5669, 44, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 5713, 83, true);

WriteLiteral("\r\n                    </li>\r\n\r\n                    <li>\r\n                        " +
"<a");

EndContext("~/Views/Shared/_Layout.cshtml", 5713, 83, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 5796, 9, true);

WriteLiteral(" href=\"#\"");

EndContext("~/Views/Shared/_Layout.cshtml", 5796, 9, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 5805, 24, true);

WriteLiteral(" class=\"dropdown-toggle\"");

EndContext("~/Views/Shared/_Layout.cshtml", 5805, 24, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 5829, 33, true);

WriteLiteral(">\r\n                            <i");

EndContext("~/Views/Shared/_Layout.cshtml", 5829, 33, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 5862, 21, true);

WriteLiteral(" class=\"icon-desktop\"");

EndContext("~/Views/Shared/_Layout.cshtml", 5862, 21, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 5883, 40, true);

WriteLiteral("></i>\r\n                            <span");

EndContext("~/Views/Shared/_Layout.cshtml", 5883, 40, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 5923, 18, true);

WriteLiteral(" class=\"menu-text\"");

EndContext("~/Views/Shared/_Layout.cshtml", 5923, 18, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 5941, 55, true);

WriteLiteral(">Administration </span>\r\n                            <b");

EndContext("~/Views/Shared/_Layout.cshtml", 5941, 55, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 5996, 30, true);

WriteLiteral(" class=\"arrow icon-angle-down\"");

EndContext("~/Views/Shared/_Layout.cshtml", 5996, 30, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 6026, 66, true);

WriteLiteral("></b>\r\n                        </a>\r\n\r\n                        <ul");

EndContext("~/Views/Shared/_Layout.cshtml", 6026, 66, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 6092, 16, true);

WriteLiteral(" class=\"submenu\"");

EndContext("~/Views/Shared/_Layout.cshtml", 6092, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 6108, 37, true);

WriteLiteral(">\r\n                            <li>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 6108, 37, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 6145, 32, true);

WriteLiteral("                                ");

EndContext("~/Views/Shared/_Layout.cshtml", 6145, 32, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 6178, 75, false);

            
            #line 154 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\Shared\_Layout.cshtml"
                           Write(Html.RouteLink("MCN", "chip", new { contoller = "Chip", action = "Index" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 6178, 75, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 6253, 73, true);

WriteLiteral("\r\n                            </li>\r\n\r\n                            <li>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 6253, 73, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 6326, 32, true);

WriteLiteral("                                ");

EndContext("~/Views/Shared/_Layout.cshtml", 6326, 32, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 6359, 95, false);

            
            #line 158 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\Shared\_Layout.cshtml"
                           Write(Html.RouteLink("Demand Status", "demandStatus", new { contoller = "Demand", action = "Index" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 6359, 95, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 6454, 149, true);

WriteLiteral("\r\n                            </li>\r\n                        </ul>\r\n             " +
"       </li>\r\n\r\n                    <li>\r\n                        <a");

EndContext("~/Views/Shared/_Layout.cshtml", 6454, 149, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 6603, 9, true);

WriteLiteral(" href=\"#\"");

EndContext("~/Views/Shared/_Layout.cshtml", 6603, 9, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 6612, 24, true);

WriteLiteral(" class=\"dropdown-toggle\"");

EndContext("~/Views/Shared/_Layout.cshtml", 6612, 24, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 6636, 33, true);

WriteLiteral(">\r\n                            <i");

EndContext("~/Views/Shared/_Layout.cshtml", 6636, 33, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 6669, 19, true);

WriteLiteral(" class=\"icon-globe\"");

EndContext("~/Views/Shared/_Layout.cshtml", 6669, 19, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 6688, 40, true);

WriteLiteral("></i>\r\n                            <span");

EndContext("~/Views/Shared/_Layout.cshtml", 6688, 40, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 6728, 18, true);

WriteLiteral(" class=\"menu-text\"");

EndContext("~/Views/Shared/_Layout.cshtml", 6728, 18, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 6746, 46, true);

WriteLiteral(">Links </span>\r\n                            <b");

EndContext("~/Views/Shared/_Layout.cshtml", 6746, 46, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 6792, 30, true);

WriteLiteral(" class=\"arrow icon-angle-down\"");

EndContext("~/Views/Shared/_Layout.cshtml", 6792, 30, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 6822, 64, true);

WriteLiteral("></b>\r\n                        </a>\r\n                        <ul");

EndContext("~/Views/Shared/_Layout.cshtml", 6822, 64, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 6886, 16, true);

WriteLiteral(" class=\"submenu\"");

EndContext("~/Views/Shared/_Layout.cshtml", 6886, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 6902, 73, true);

WriteLiteral(">\r\n                            <li>\r\n\r\n                                <a");

EndContext("~/Views/Shared/_Layout.cshtml", 6902, 73, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 6975, 185, true);

WriteLiteral(" href=\"https://qlikview.qualcomm.com/QvAJAXZfc/AccessPoint.aspx?open=&id=QVS%40qv" +
"prdcluster%7CQCT%20Operations%2FQCT%20Operation%2FSD%20Inventory%20by%20Item%20R" +
"eport.qvw&client=Plugin\"");

EndContext("~/Views/Shared/_Layout.cshtml", 6975, 185, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 7160, 16, true);

WriteLiteral(" target=\"_blank\"");

EndContext("~/Views/Shared/_Layout.cshtml", 7160, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 7176, 41, true);

WriteLiteral(">\r\n                                    <i");

EndContext("~/Views/Shared/_Layout.cshtml", 7176, 41, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 7217, 32, true);

WriteLiteral(" class=\"icon-double-angle-right\"");

EndContext("~/Views/Shared/_Layout.cshtml", 7217, 32, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 7249, 230, true);

WriteLiteral("></i>\r\n                                    Bldg W - GTC Inventory(IE preferred br" +
"owser)\r\n                                </a>\r\n                            </li>\r" +
"\n                            <li>\r\n                                <a");

EndContext("~/Views/Shared/_Layout.cshtml", 7249, 230, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 7479, 120, true);

WriteLiteral(" href=\"http://qualnet.qualcomm.com/Departments/qct/qct_maintwork/Manuals/Vertical" +
"_Rack/Full_inventory_with_checkout.xls\"");

EndContext("~/Views/Shared/_Layout.cshtml", 7479, 120, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 7599, 16, true);

WriteLiteral(" target=\"_blank\"");

EndContext("~/Views/Shared/_Layout.cshtml", 7599, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 7615, 41, true);

WriteLiteral(">\r\n                                    <i");

EndContext("~/Views/Shared/_Layout.cshtml", 7615, 41, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 7656, 32, true);

WriteLiteral(" class=\"icon-double-angle-right\"");

EndContext("~/Views/Shared/_Layout.cshtml", 7656, 32, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 7688, 199, true);

WriteLiteral("></i>\r\n                                    VLM Inventory\r\n                       " +
"         </a>\r\n                            </li>\r\n                            <l" +
"i>\r\n                                <a");

EndContext("~/Views/Shared/_Layout.cshtml", 7688, 199, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 7887, 67, true);

WriteLiteral(" href=\"https://sfdc.qualcomm.com/mqds/mqdsRequest/viewMqdsRequests\"");

EndContext("~/Views/Shared/_Layout.cshtml", 7887, 67, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 7954, 16, true);

WriteLiteral(" target=\"_blank\"");

EndContext("~/Views/Shared/_Layout.cshtml", 7954, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 7970, 41, true);

WriteLiteral(">\r\n                                    <i");

EndContext("~/Views/Shared/_Layout.cshtml", 7970, 41, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 8011, 32, true);

WriteLiteral(" class=\"icon-double-angle-right\"");

EndContext("~/Views/Shared/_Layout.cshtml", 8011, 32, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 8043, 230, true);

WriteLiteral("></i>\r\n                                    MQDS Dashboard - Bldg W back end proce" +
"ssing \r\n                                </a>\r\n                            </li>\r" +
"\n                            <li>\r\n                                <a");

EndContext("~/Views/Shared/_Layout.cshtml", 8043, 230, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 8273, 69, true);

WriteLiteral(" href=\"http://maintdb.qualcomm.com/Materials/MemoryStackRequest.asp \"");

EndContext("~/Views/Shared/_Layout.cshtml", 8273, 69, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 8342, 16, true);

WriteLiteral(" target=\"_blank\"");

EndContext("~/Views/Shared/_Layout.cshtml", 8342, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 8358, 41, true);

WriteLiteral(">\r\n                                    <i");

EndContext("~/Views/Shared/_Layout.cshtml", 8358, 41, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 8399, 32, true);

WriteLiteral(" class=\"icon-double-angle-right\"");

EndContext("~/Views/Shared/_Layout.cshtml", 8399, 32, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 8431, 199, true);

WriteLiteral("></i>\r\n                                    Stack Request\r\n                       " +
"         </a>\r\n                            </li>\r\n                            <l" +
"i>\r\n                                <a");

EndContext("~/Views/Shared/_Layout.cshtml", 8431, 199, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 8630, 184, true);

WriteLiteral(" href=\"https://qlikview.qualcomm.com/QvAJAXZfc/AccessPoint.aspx?open=&id=QVS%40qv" +
"prdcluster%7CQCT%20Operations%2FQCT%20Operation%2FTest%20Hardware%20INV%20on%20H" +
"and.qvw&client=Plugin \"");

EndContext("~/Views/Shared/_Layout.cshtml", 8630, 184, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 8814, 16, true);

WriteLiteral(" target=\"_blank\"");

EndContext("~/Views/Shared/_Layout.cshtml", 8814, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 8830, 199, true);

WriteLiteral(">Bldg M - Corp Oracle Inventory (IE preferred browser)\r\n                         " +
"       </a>\r\n                            </li>\r\n\r\n                            <l" +
"i>\r\n                                <a");

EndContext("~/Views/Shared/_Layout.cshtml", 8830, 199, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 9029, 90, true);

WriteLiteral(" href=\"file:///\\\\maintdb\\wwwroot\\Materials\\Dox\\Surf_FFA Chip Forecast CD90CP90 Le" +
"vel.xlsx\"");

EndContext("~/Views/Shared/_Layout.cshtml", 9029, 90, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 9119, 16, true);

WriteLiteral(" target=\"_blank\"");

EndContext("~/Views/Shared/_Layout.cshtml", 9119, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 9135, 177, true);

WriteLiteral(">Chip Forecast - CD90\\CP90 Level\r\n                                </a>\r\n         " +
"                   </li>\r\n\r\n                            <li>\r\n                  " +
"              <a");

EndContext("~/Views/Shared/_Layout.cshtml", 9135, 177, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 9312, 131, true);

WriteLiteral(" href=\"https://projects.qualcomm.com/sites/ENG_TECHs/Lists/Incoming%20Deliveries%" +
"20Special%20Allocation%20or%20Stock/AllItems.aspx\"");

EndContext("~/Views/Shared/_Layout.cshtml", 9312, 131, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 9443, 16, true);

WriteLiteral(" target=\"_blank\"");

EndContext("~/Views/Shared/_Layout.cshtml", 9443, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 9459, 233, true);

WriteLiteral(">Incoming Deliveries(Special Allocation\\etc)</a>\r\n                            </l" +
"i>\r\n\r\n\r\n                        </ul>\r\n\r\n                    </li>\r\n\r\n          " +
"      </ul>\r\n                <!-- /.nav-list -->\r\n\r\n                <div");

EndContext("~/Views/Shared/_Layout.cshtml", 9459, 233, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 9692, 25, true);

WriteLiteral(" class=\"sidebar-collapse\"");

EndContext("~/Views/Shared/_Layout.cshtml", 9692, 25, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 9717, 22, true);

WriteLiteral(" id=\"sidebar-collapse\"");

EndContext("~/Views/Shared/_Layout.cshtml", 9717, 22, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 9739, 25, true);

WriteLiteral(">\r\n                    <i");

EndContext("~/Views/Shared/_Layout.cshtml", 9739, 25, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 9764, 31, true);

WriteLiteral(" class=\"icon-double-angle-left\"");

EndContext("~/Views/Shared/_Layout.cshtml", 9764, 31, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 9795, 36, true);

WriteLiteral(" data-icon1=\"icon-double-angle-left\"");

EndContext("~/Views/Shared/_Layout.cshtml", 9795, 36, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 9831, 37, true);

WriteLiteral(" data-icon2=\"icon-double-angle-right\"");

EndContext("~/Views/Shared/_Layout.cshtml", 9831, 37, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 9868, 56, true);

WriteLiteral("></i>\r\n                </div>\r\n\r\n                <script");

EndContext("~/Views/Shared/_Layout.cshtml", 9868, 56, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 9924, 23, true);

WriteLiteral(" type=\"text/javascript\"");

EndContext("~/Views/Shared/_Layout.cshtml", 9924, 23, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 9947, 154, true);

WriteLiteral(">\r\n                    try { ace.settings.check(\'sidebar\', \'collapsed\') } catch (" +
"e) { }\r\n                </script>\r\n            </div>\r\n\r\n            <div");

EndContext("~/Views/Shared/_Layout.cshtml", 9947, 154, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 10101, 21, true);

WriteLiteral(" class=\"main-content\"");

EndContext("~/Views/Shared/_Layout.cshtml", 10101, 21, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 10122, 23, true);

WriteLiteral(">\r\n                <div");

EndContext("~/Views/Shared/_Layout.cshtml", 10122, 23, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 10145, 20, true);

WriteLiteral(" class=\"breadcrumbs\"");

EndContext("~/Views/Shared/_Layout.cshtml", 10145, 20, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 10165, 17, true);

WriteLiteral(" id=\"breadcrumbs\"");

EndContext("~/Views/Shared/_Layout.cshtml", 10165, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 10182, 30, true);

WriteLiteral(">\r\n                    <script");

EndContext("~/Views/Shared/_Layout.cshtml", 10182, 30, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 10212, 23, true);

WriteLiteral(" type=\"text/javascript\"");

EndContext("~/Views/Shared/_Layout.cshtml", 10212, 23, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 10235, 149, true);

WriteLiteral(">\r\n                        try { ace.settings.check(\'breadcrumbs\', \'fixed\') } cat" +
"ch (e) { }\r\n                    </script>\r\n\r\n                    <ul");

EndContext("~/Views/Shared/_Layout.cshtml", 10235, 149, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 10384, 19, true);

WriteLiteral(" class=\"breadcrumb\"");

EndContext("~/Views/Shared/_Layout.cshtml", 10384, 19, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 10403, 63, true);

WriteLiteral(">\r\n                        <li>\r\n                            <i");

EndContext("~/Views/Shared/_Layout.cshtml", 10403, 63, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 10466, 18, true);

WriteLiteral(" class=\"icon-home\"");

EndContext("~/Views/Shared/_Layout.cshtml", 10466, 18, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 10484, 7, true);

WriteLiteral("></i>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 10484, 7, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 10491, 28, true);

WriteLiteral("                            ");

EndContext("~/Views/Shared/_Layout.cshtml", 10491, 28, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 10520, 80, false);

            
            #line 235 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\Shared\_Layout.cshtml"
                       Write(Html.RouteLink("GTW", "GTW", new { controller = "ChipRequest", action = "GTW" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 10520, 80, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 10600, 64, true);

WriteLiteral(">\r\n                        </li>\r\n                        <li>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 10600, 64, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 10664, 28, true);

WriteLiteral("                            ");

EndContext("~/Views/Shared/_Layout.cshtml", 10664, 28, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 10693, 13, false);

            
            #line 238 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\Shared\_Layout.cshtml"
                       Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 10693, 13, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 10706, 194, true);

WriteLiteral("\r\n                        </li>\r\n                    </ul>\r\n                    <" +
"!-- .breadcrumb -->\r\n\r\n\r\n                    <!-- #nav-search -->\r\n             " +
"   </div>\r\n\r\n                <div");

EndContext("~/Views/Shared/_Layout.cshtml", 10706, 194, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 10900, 21, true);

WriteLiteral(" class=\"page-content\"");

EndContext("~/Views/Shared/_Layout.cshtml", 10900, 21, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 10921, 27, true);

WriteLiteral(">\r\n                    <div");

EndContext("~/Views/Shared/_Layout.cshtml", 10921, 27, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 10948, 20, true);

WriteLiteral(" class=\"page-header\"");

EndContext("~/Views/Shared/_Layout.cshtml", 10948, 20, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 10968, 96, true);

WriteLiteral(">\r\n                        <h1>Web Page\r\n\t\t\t\t\t\t\t\t<small>\r\n                       " +
"             <i");

EndContext("~/Views/Shared/_Layout.cshtml", 10968, 96, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 11064, 32, true);

WriteLiteral(" class=\"icon-double-angle-right\"");

EndContext("~/Views/Shared/_Layout.cshtml", 11064, 32, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 11096, 7, true);

WriteLiteral("></i>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 11096, 7, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 11103, 36, true);

WriteLiteral("                                    ");

EndContext("~/Views/Shared/_Layout.cshtml", 11103, 36, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 11140, 13, false);

            
            #line 252 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\Shared\_Layout.cshtml"
                               Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 11140, 13, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 11153, 173, true);

WriteLiteral("\r\n                                </small>\r\n                        </h1>\r\n      " +
"              </div>\r\n                    <!-- /.page-header -->\r\n\r\n            " +
"        <div");

EndContext("~/Views/Shared/_Layout.cshtml", 11153, 173, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 11326, 18, true);

WriteLiteral(" class=\"container\"");

EndContext("~/Views/Shared/_Layout.cshtml", 11326, 18, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 11344, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 11344, 3, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 11347, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Shared/_Layout.cshtml", 11347, 24, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 11372, 12, false);

            
            #line 259 "\\maintdb1-dev\inetpub\wwwroot\Development\MvcChipRequest\MvcChipRequest\Views\Shared\_Layout.cshtml"
                   Write(RenderBody());

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 11372, 12, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 11384, 219, true);

WriteLiteral("\r\n                    </div>\r\n                    <!-- /.page-content -->\r\n      " +
"          </div>\r\n                <!-- /.main-content -->\r\n            </div>\r\n " +
"           <!-- /.main-container-inner -->\r\n            <a");

EndContext("~/Views/Shared/_Layout.cshtml", 11384, 219, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 11603, 9, true);

WriteLiteral(" href=\"#\"");

EndContext("~/Views/Shared/_Layout.cshtml", 11603, 9, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 11612, 19, true);

WriteLiteral(" id=\"btn-scroll-up\"");

EndContext("~/Views/Shared/_Layout.cshtml", 11612, 19, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 11631, 45, true);

WriteLiteral(" class=\"btn-scroll-up btn btn-sm btn-inverse\"");

EndContext("~/Views/Shared/_Layout.cshtml", 11631, 45, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 11676, 21, true);

WriteLiteral(">\r\n                <i");

EndContext("~/Views/Shared/_Layout.cshtml", 11676, 21, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 11697, 50, true);

WriteLiteral(" class=\"icon-double-angle-up icon-only bigger-110\"");

EndContext("~/Views/Shared/_Layout.cshtml", 11697, 50, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 11747, 104, true);

WriteLiteral("></i>\r\n            </a>\r\n        </div>\r\n    </div>\r\n\r\n    <!-- /.main-container " +
"-->\r\n</body>\r\n</html>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 11747, 104, true);

        }
    }
}
