// <auto-generated />
namespace CleanRoom.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addProj : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addProj));
        
        string IMigrationMetadata.Id
        {
            get { return "201311290901257_addProj"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
