// <auto-generated />
namespace CleanRoom.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addProjFoundryDDListsToWLot2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addProjFoundryDDListsToWLot2));
        
        string IMigrationMetadata.Id
        {
            get { return "201312062133194_addProjFoundryDDListsToWLot2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
