// <auto-generated />
namespace CleanRoom.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddLabeltoWL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLabeltoWL));
        
        string IMigrationMetadata.Id
        {
            get { return "201311261808528_AddLabeltoWL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
