// <auto-generated />
namespace Guestbook.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddUnknown : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddUnknown));
        
        string IMigrationMetadata.Id
        {
            get { return "201303081723221_AddUnknown"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
